searchSpace:
  mlp_layer: 
    _type: choice
    _value: [[64,64,64],[128,128,128],[256,256,256]]
  dropout:
   _type: choice
   _value: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
  batch_norm:
    _type: choice
    _value: [true, false]
experimentName: Benchmark-DCN
trialCommand: python3 ../../test/test_quickrun.py
trialGpuNumber: 1
trialConcurrency: 2
maxExperimentDuration: 24h
maxTrialNumber: 100
experimentWorkingDirectory: nni-experiments
tuner:                          # Configure the tuning algorithm.
  name: TPE                     # Supported algorithms: TPE, Random, Anneal, Evolution, GridSearch, GPTuner, PBTTuner, etc.
                                #   Full list:  https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html
  classArgs:                    # Algorithm specific arguments. See the tuner's doc for details.
    optimize_mode: maximize     #   "minimize" or "maximize"
trainingService:
  platform: local
  useActiveGpu: false
  gpuIndices: 0
  maxTrialNumberPerGpu: 2