searchSpace:
  mlp_layer_0: 
    _type: choice
    _value: [64, 128, 256]
  mlp_layer_1:
    _type: choice
    _value: [64, 128, 256]
  mlp_layer_2:
    _type: choice
    _value: [64, 128, 256]
  num_layers:
    _type: choice
    _value: [2,3,4,5,6,7,8,9,10]
  embed_dim:
    _type: choice
    _value: [10, 20, 30]
  dropout:
   _type: choice
   _value: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
  batch_norm:
    _type: choice
    _value: [true, false]
experimentName: Benchmark-DCN
trialCommand: python3 ../../test/test_quickrun.py
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 24h
maxTrialNumber: 100
experimentWorkingDirectory: nni-experiments
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True