fs:
  name: AdaFS
  retrain: False
  retrain_prepare: False
  optimization: DARTS
  retrain_reinitialize: False
  before_train_prepare: False
  reinitialize: all
  update_frequency: 5
  pretrain_epoch_num: 3 # the pretrain epochs mentioned in paper