authorName: default
experimentName: DCN
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local
useAnnotation: false
searchSpacePath: dcn.json
tuner:
  builtinTunerName: TPE
trial:
  command: python ~/work/FS-Emb-Benchmark-main/test/test_quickrun.py
  codeDir: ~/work/FS-Emb-Benchmark-main
  gpuNum: 1